##### PUT: Update a person's phone number
PUT http://localhost:3001/api/persons/6757805af01465571f707dba
Content-Type: application/json

{
    "name": "Mary Poppendieck",
    "number": "55-45345678"
}